config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'


  # below 3 lines did for deleting photo object, follow up in photo controller
  
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :update, :edit, :show ] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end


  post 'braintree/checkout'
  root 'listings#index'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  # resources :listings, controller: "listings"
  resources :listings do
    resources :photos, only: [:create, :destroy]
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:destroy] do
    resources :braintree, only: [:new, :create]
  end
  # resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  # resource :session, controller: "clearance/sessions", only: [:create]

  # resources :users, controller: "clearance/users", only: [:create] do
  #   resource :password,
  #     controller: "clearance/passwords",
  #     only: [:create, :edit, :update]
  # end

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :bookings

  paginates_per 10

  enum verified: [:unverified, :verified]
  # mount_uploaders :photos, PhotoUploader
  # serialize :photos, JSON
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    # @listings = Listing.all
    @listings = Listing.order(:name).page params[:page]
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @booking = @listing.bookings.new
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    
    respond_to do |format|
      store_photos
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit( :name, :description, :price, :num_of_bed, :address)
    end

    def store_photos
      photos = params[:listing][:photos]
      photos.each{|photo| @listing.photos.create(image: photo)} if photos
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(listing) do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :num_of_bed %>
    <%= f.number_field :num_of_bed %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :photos %>
    <%= f.file_field :photos, multiple: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Hoster</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Num of bed</th>
      <th>Address</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.user.name %></td>
        <td><%= listing.name %></td>
        <td><%= listing.description %></td>
        <td><%= listing.price %></td>
        <td><%= listing.num_of_bed %></td>
        <td><%= listing.address %></td>
        <% if listing.verified? %>
        <td><i class="fa fa-check" aria-hidden="true"></i></td>
        <% end %>
        <td><%= link_to 'Show', listing %></td>

        <% if signed_in? -%>
      <%if listing.user.id == current_user.id %>
          <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
          <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
        <% end -%>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @listings %>
<br>

    <% if signed_in? -%>
      <%= link_to 'New Listing', new_listing_path %>
    <% else -%>
     <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>

app/views/listings/new.html.erb
<h1>New Listing</h1>




    <% if signed_in? -%>
      <%= render 'form', listing: @listing %>
	  <%= link_to 'Back', listings_path %>
    <% else -%>
      <p>Please sign in to list </p>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @listing.user.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Num of bed:</strong>
  <%= @listing.num_of_bed %>
</p>

<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<% if @listing.photos.first != nil %>
<p>
  <strong>Photos:</strong> 
  
  <div class="container">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">

         <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <% t = @listing.photos.length-1 %>
          <% for y in 1..t do%>
          <li data-target="#myCarousel" data-slide-to="<%= y %>"></li>
          <% end %>
        </ol>
    <!-- Wrapper for slides -->
      
     <div class="carousel-inner">
        
           <div class="item active">
           <%= image_tag @listing.photos.first.image.to_s %>
            
           </div>

          <% for i in 1..t do%>
         <div class="item">

         <%= image_tag @listing.photos[i].image.to_s %>
            
         
         </div>

     <% end %>  
         
       </div>

       <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
</p>
<%end%>


<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>
<br>
<%= render partial: "bookings/form" %>