config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'


  # below 3 lines did for deleting photo object, follow up in photo controller
  
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :update, :edit, :show ] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end


  post 'braintree/checkout'
  root 'listings#index'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  # resources :listings, controller: "listings"
  resources :listings do
    resources :photos, only: [:create, :destroy]
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:destroy] do
    resources :braintree, only: [:new, :create]
  end
  # resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  # resource :session, controller: "clearance/sessions", only: [:create]

  # resources :users, controller: "clearance/users", only: [:create] do
  #   resource :password,
  #     controller: "clearance/passwords",
  #     only: [:create, :edit, :update]
  # end

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# require 'carrierwave/orm/activerecord'


class User < ApplicationRecord
  include Clearance::User

  mount_uploader :avatar, AvatarUploader

  enum access_level: [:customer, :moderator, :superadmin]

  has_many :authentications, :dependent => :destroy
  has_many :listings , :dependent => :destroy
  has_many :bookings , :dependent => :destroy

  # validates :age, presence: true
  validates :name, presence: true

  def self.create_with_auth_and_hash(authentication, auth_hash)
      user = User.create!(name: auth_hash["extra"]["raw_info"]["name"],age: auth_hash["extra"]["raw_info"]["age_range"].min[1], email: auth_hash["extra"]["raw_info"]["email"], password: SecureRandom.hex(4))
      user.authentications << (authentication)      
      return user
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end
end
 

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
	def new
		@user = User.new  # = user_from_params
		# render template: "users/new"
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			redirect_back_or url_after_create
		else
			# @user.save
			respond_to do |format|
				format.html {render template: "user/new"}
				format.js 
			end
			# render template: "user/new"
		end
	end

	def index 
		render 'homepage/index'
	end	

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		respond_to do |format|
		if @user.update(user_params)
		 format.html { redirect_to @user, notice: 'User was successfully updated.' }        
      else
        format.html { render :edit }
        
      end
  	end
	end

	def show
		@user = User.find(params[:id])
		@bookings = @user.bookings
	end
	
	private
	def user_params
		params.require(:user).permit(:name, :age, :email, :password, :avatar, :remove_avatar)
	end
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

  <div class="text-field">
  <%= form.label :name %>
  <%= form.text_field :name %>
  </div>

  <div class="text-field">
  <%= form.label :age %>
  <%= form.text_field :age %>
</div>

<div class="text-field">
  <%= form.label :avatar %>
  <%= form.file_field :avatar %>
</div>

<p>
    <label>
      <%= form.check_box :remove_avatar %>
      Remove avatar
    </label>
  </p>

app/views/users/create.js.erb
$('#error'). html('<p><%= @user.errors.full_messages %></p>');

app/views/users/edit.html.erb
<%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit "Edit", class:"btn btn-primary" %>
    </div>

 <%end%>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user, remote: true, authenticity_token: true do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit "Submit", class:"btn btn-primary" %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

<div id= 'error'></div>

app/views/users/show.html.erb
<p>Ma hai edited</p>


<%= image_tag @user.avatar.url, class: 'circle thumb' %>
<br>
<h1><%= @user.name %></h1>
<br>
<%= @user.email %>

<table>
	<col width="200px" />
    <col width="200px" />
    <col width="200px" />
<tr>
	<th >Listing Title</th>
	<th>Start date</th>
	<th>End date</th>
	<th>Guests</th>
	<th>Price</th>
	<td>Action</td>
	<td>Pay</td>
</tr>
	<% @bookings.each do |x| %>
	<tr>
		<td ><%= link_to x.listing.name, x.listing %></td>
		<td><%=x.start_date%></td>
		<td><%=x.end_date%></td>
		<td><%=x.num_of_guest%></td>
		<td><%=x.total_price %></td>
		<td><%= link_to "Cancel booking", x, method: :delete %></td>
		<td><%= link_to "Payment page", new_booking_braintree_path(x) %></td>
	</tr>
	<%end%>
</table>

<%= link_to "Make Payment", braintree_new_path %>