config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'


  # below 3 lines did for deleting photo object, follow up in photo controller
  
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :update, :edit, :show ] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end


  post 'braintree/checkout'
  root 'listings#index'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  # resources :listings, controller: "listings"
  resources :listings do
    resources :photos, only: [:create, :destroy]
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:destroy] do
    resources :braintree, only: [:new, :create]
  end
  # resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  # resource :session, controller: "clearance/sessions", only: [:create]

  # resources :users, controller: "clearance/users", only: [:create] do
  #   resource :password,
  #     controller: "clearance/passwords",
  #     only: [:create, :edit, :update]
  # end

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- CSS -->
  <!-- a) bootstrap.min.css -->
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!--  **I park application.css after bootstrap cdn link so that application.css setting can override bootstrap stylesss-->
  
  <!-- JS -->
  <!-- a) Jquery.min.js -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- b) bootstrap.min.js -->
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <!-- c) braintree.js -->
  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
  <!-- d) fontawesome.js -->
  <script src="https://use.fontawesome.com/b470fc1405.js"></script>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="header">
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>